### ISSUE TITLE
[iOS] 프로젝트 설정 

### ISSUE THREAD

**Issue by JasonLee0223** [honeySleepr/airbnb_team-05#1]
## 📝 todo
- [x] develop-iOS PR 브랜치 생성
- [x] 프로젝트 설정할 브랜치 생성
- [x] 프로젝트 생성 및 .gitignore 작성
- [x] 전체적인 필요한 속성 분류하여 도식화
- [x] 한 주 계획세우기
