### ISSUE TITLE
[iOS] NavigationBar 구현하기

### ISSUE THREAD

**Issue by JasonLee0223** [honeySleepr/airbnb_team-05#3]
## 📝 todo
- [x] NavigationBar Title 탭에 맞춰 변경
- [x] SearchBar 생성
   - [x] searchBar를 사용하여 기본 동작 확인
   - [x] UISearchController를 사용하여 생성
